BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: 'Clear'
            on_release: app.handle_clear()
        TextInput:
            id: input_name
            text: ' '
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: 'Greet'
            on_press: app.handle_greet()
        Label:
            id: output_label
            color: (1,1,0,1)